services:
  saam-db:
    image: postgres:15
    container_name: saam-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=challenge
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - saam-network

  saam-api:
    container_name: saam-api
    build:
      context: ./api
      dockerfile: docker/Dockerfile.dev
    networks:
      - saam-network
    depends_on:
      - saam-db
    ports:
      - "8080:8080"

  saam-frontend:
    container_name: saam-frontend
    build:
      context: ./front-end
      dockerfile: docker/Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./front-end:/app
      - /app/node_modules
    networks:
      - saam-network
    depends_on:
      - saam-api

networks:
  saam-network:
    driver: bridge

volumes:
  postgres_data:
